### ISSUE TITLE
Change popup (identify) for Community layers

### ISSUE THREAD

**Issue by brosenbaum** [Innovate-Inc/EnviroAtlas#314] opened 2017-01-13 18:23 UTC
Popups/identify shows HUC12 when community layer drawn. Should be "Census block group:"
![communitypopup](https://cloud.githubusercontent.com/assets/6422486/21940696/5631f2ee-d97a-11e6-8077-5c5ff44ad636.PNG)

**Comment by torrin47** [comment] 2017-01-13 20:36
Duplicate of issue #289

**Closed** 2017-01-18 17:57 UTC
