### ISSUE TITLE
Reorganize widgets and widget drawers on main map

### ISSUE THREAD

**Issue by brosenbaum** [Innovate-Inc/EnviroAtlas#313] opened 2017-01-13 18:17 UTC
Reorganize widget groups along top as follows:
**- Basemaps**
**- Community Selection (Icon TBD)**
**- Mapping Tools (icon "Geoprocessing toolbox")**
_1. Bookmarks
2. Print
3. Save Session
4. Draw & Measure_
**- Analytical Tools (icon TBD)**
_1. ECAT (Icon TBD)
2. Raindrop (icon "Stream")
3. Elevation Profile
4. Time Series Widget (a.k.a. FSViewer) (icon "Time Slider")_
**- Add Data (icon TBD)  - list is as currently set.**

**Comment by torrin47** [comment] 2017-01-13 20:38
Sounds good - where does onscreen "LayerList Widget" belong?  On its own or grouped with Basemaps?

**Comment by brosenbaum** [comment] 2017-01-13 20:44
Good question! probably wherever PBS/demographics end up. they had talked about down the left side under the navigation/home buttons.

**Comment by David-Yarnell** [comment] 2017-02-02 18:00
I was able to produce unexpected behavior with the drawer widget. If a drawer widget is opened and one of the widgets inside is then opened and then closed. The drawer widget then takes several clicks to open back up. I'm not completely sure what the issue is but thought it should documented.

**Comment by torrin47** [comment] 2017-02-03 00:53
Yes, no question this behavior (bug) was introduced when I made the tweak to allow more than one widget to stay visible at a time.  Somehow the drawer widget disappears but the parent button thinks it's still open, and it takes a full cycle to reset. Any idea how we might go about triggering the equivalent "close" event? Or instead prevent the drawer widget from autoclosing, so it doesn't get out of sync?

**Comment by David-Yarnell** [comment] 2017-02-03 18:11
I originally wrote code in the drawer widget to auto-close but it doesn't seem like it is actually closing the widget. For now I will prevent the drawer widget from autoclosing.

**Closed** 2017-03-01 17:38 UTC
Labels: enhancement, MVP, tools
