### ISSUE TITLE
Drawer icons get jumbled when window is resized.

### ISSUE THREAD

**Issue by brosenbaum** [Innovate-Inc/EnviroAtlas#362] opened 2017-03-13 13:59 UTC
it is common that the screen is often resized for presentations on low-res projectors. When the wab is resized to fill the screen, the icons get placed in odd locations. Need to test or fix so icons moved off of the main screen remain "hidden" or off screen when resized.

**Comment by torrin47** [comment] 2017-03-22 16:55
Duplicate of #331

**Closed by torrin47** 2017-03-22 16:55 UTC
Labels: MVP, tools
